//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by hancock.rc
//
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDS_RIBBON_MAKEMODEL            101
#define IDS_RIBBON_EXTRBUFFERS          102
#define IDS_RIBBON_MAKEINDEX            103
#define IDS_RIBBON_LABELGOOD            104
#define IDS_RIBBON_PRUNE                105
#define IDS_RIBBON_MERGE                106
#define IDS_RIBBON_COMPILE              107
#define IDS_RIBBON_MAKESTUB             108
#define IDS_RIBBON_LABELMODEL           109
#define IDB_WRITESMALL                  110
#define IDS_RIBBON_LOCSIGS              110
#define IDB_WRITELARGE                  111
#define IDS_RIBBON_LABELINDEX           111
#define IDB_MAIN                        112
#define IDS_RIBBON_PREPROC              112
#define IDB_BUTTONS                     113
#define IDS_RIBBON_LABELMALWARE         113
#define IDB_FILELARGE                   114
#define IDS_RIBBON_CLSTFILES            114
#define IDB_FILESMALL                   115
#define IDS_RIBBON_LABELPREMALWARE      115
#define IDS_RIBBON_LABELCLUSTER         116
#define IDS_RIBBON_LABELSTUBMAP         117
#define IDS_LABELFINDSIGS               118
#define IDS_RIBBON_LABELFINDSIGS        118
#define IDR_POPUP_EDIT                  119
#define IDS_RIBBON_SCHEDULER            119
#define ID_STATUSBAR_PANE1              120
#define IDS_RIBBON_LOGGING              120
#define ID_STATUSBAR_PANE2              121
#define IDS_RIBBON_VIEWSCHED            121
#define IDS_STATUS_PANE1                122
#define IDS_STATUS_PANE2                123
#define IDS_RIBBON_VIEWLOG              124
#define IDS_RIBBON_LOGSAVE              125
#define IDS_RIBBON_VIEWRPANE            126
#define IDR_MAINFRAME                   128
#define IDR_MAINFRAME_256               129
#define IDR_hancockTYPE                 130
#define IDR_PASTE_MENU                  151
#define IDR_WINDOWS_MENU                152
#define ID_VIEW_NAVIGATION              185
#define IDB_NAVIGATION_LARGE            186
#define IDB_NAVIGATION_LARGE_HC         187
#define IDB_PAGES                       188
#define IDB_PAGES_HC                    189
#define IDB_PAGES_SMALL                 190
#define IDB_PAGES_SMALL_HC              191
#define IDS_MYCALENDARS                 250
#define IDS_CALENDAR                    251
#define IDS_SHORTCUTS                   252
#define IDS_FOLDERS                     253
#define IDS_OUTLOOKBAR                  258
#define IDS_RIBBON_FILE                 260
#define IDS_RIBBON_NEW                  262
#define IDS_RIBBON_OPEN                 263
#define IDS_RIBBON_SAVE                 264
#define IDS_RIBBON_SAVEAS               265
#define IDS_RIBBON_PRINT                266
#define IDS_RIBBON_PRINT_LABEL          267
#define IDS_RIBBON_PRINT_QUICK          268
#define IDS_RIBBON_PRINT_PREVIEW        269
#define IDS_RIBBON_PRINT_SETUP          270
#define IDS_RIBBON_CLOSE                271
#define IDS_RIBBON_RECENT_DOCS          272
#define IDS_RIBBON_EXIT                 273
#define IDS_RIBBON_HOME                 274
#define IDS_RIBBON_CLIPBOARD            275
#define IDS_RIBBON_PASTE                276
#define IDS_RIBBON_CUT                  277
#define IDS_RIBBON_COPY                 278
#define IDS_RIBBON_SELECTALL            279
#define IDS_RIBBON_WINDOW               284
#define IDS_RIBBON_WINDOWS              285
#define IDS_RIBBON_STYLE                286
#define IDS_RIBBON_STYLE_TIP            287
#define IDS_RIBBON_STYLE_DESC           288
#define IDS_RIBBON_STATUSBAR            289
#define IDS_RIBBON_VIEW                 290
#define IDS_RIBBON_ACTIONS              291
#define IDS_RIBBON_TOOLS                292
#define IDS_RIBBON_FILETYPES            293
#define IDS_EDIT_MENU                   306
#define IDS_RIBBON_GOODWARE             310
#define IDS_RIBBON_MODELS               311
#define IDS_RIBBON_INDECES              312
#define IDD_LOGUI                       312
#define IDS_RIBBON_MALWARE              313
#define IDS_RIBBON_PREMALWARE           314
#define IDS_RIBBON_CLUSTERINGS          315
#define IDS_RIBBON_STUBMAPS             316
#define IDS_RIBBON_FINDOUTPUT           317
#define IDS_RIBBON_UNLABELED            318
#define IDC_LOGLIST                     1001
#define IDC_LOGTEXT                     1002
#define ID_WRITE_PASTEASHYPERLINK       32770
#define ID_VIEW_GROAR                   32771
#define ID_VIEW_GOODWARE                32772
#define IDM_VIEW_GROAR                  32773
#define IDM_VIEW_GOODWARE               32774
#define ID_VIEW_MALWARE                 32775
#define IDM_VIEW_MODELS                 32776
#define ID_VIEW_INDECES                 32777
#define IDM_VIEW_INDECES                32778
#define ID_VIEW_MALWARE32779            32779
#define IDM_VIEW_MALWARE32779           32780
#define ID_VIEW_CLUSTERINGS             32781
#define IDM_VIEW_CLUSTERINGS            32782
#define ID_VIEW_STUBMAPS                32783
#define IDM_VIEW_STUBMAPS               32784
#define ID_VIEW_FINDSIGNATURESOUTPUT    32785
#define ID_VIEW_UNCLASSIFIED            32786
#define IDM_VIEW_FINDSIGS               32787
#define IDM_VIEW_UNCLASSIFIED           32788

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        313
#define _APS_NEXT_COMMAND_VALUE         32789
#define _APS_NEXT_CONTROL_VALUE         1003
#define _APS_NEXT_SYMED_VALUE           310
#endif
#endif
