//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by hancock.rc
//
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDS_RIBBON_MAKEMODEL            101
#define IDS_RIBBON_EXTRBUFFERS          102
#define IDS_RIBBON_MAKEINDEX            103
#define IDS_RIBBON_LABELGOOD            104
#define IDS_RIBBON_PRUNE                105
#define IDS_RIBBON_MERGE                106
#define IDS_RIBBON_COMPILE              107
#define IDS_RIBBON_MAKESTUB             108
#define IDS_RIBBON_LABELMODEL           109
#define IDB_WRITESMALL                  110
#define IDS_RIBBON_LOCSIGS              110
#define IDB_WRITELARGE                  111
#define IDS_RIBBON_LABELINDEX           111
#define IDB_MAIN                        112
#define IDS_RIBBON_PREPROC              112
#define IDB_BUTTONS                     113
#define IDS_RIBBON_LABELMALWARE         113
#define IDB_FILELARGE                   114
#define IDS_RIBBON_CLSTFILES            114
#define IDB_FILESMALL                   115
#define IDS_RIBBON_LABELPREMALWARE      115
#define IDS_RIBBON_LABELCLUSTER         116
#define IDS_RIBBON_LABELSTUBMAP         117
#define IDS_LABELFINDSIGS               118
#define IDS_RIBBON_LABELFINDSIGS        118
#define IDR_POPUP_EDIT                  119
#define IDS_RIBBON_SCHEDULER            119
#define ID_STATUSBAR_PANE1              120
#define IDS_RIBBON_LOGGING              120
#define ID_STATUSBAR_PANE2              121
#define IDS_RIBBON_VIEWSCHED            121
#define IDS_STATUS_PANE1                122
#define IDS_STATUS_PANE2                123
#define IDS_RIBBON_VIEWLOG              124
#define IDS_RIBBON_LOGSAVE              125
#define IDS_RIBBON_VIEWRPANE            126
#define IDS_RIBBON_THRESHOLD            127
#define IDR_MAINFRAME                   128
#define IDR_MAINFRAME_256               129
#define IDS_RIBBON_LABELUNC             129
#define IDR_hancockTYPE                 130
#define IDR_PASTE_MENU                  151
#define IDR_WINDOWS_MENU                152
#define ID_VIEW_NAVIGATION              185
#define IDB_NAVIGATION_LARGE            186
#define IDB_NAVIGATION_LARGE_HC         187
#define IDB_PAGES                       188
#define IDB_PAGES_HC                    189
#define IDB_PAGES_SMALL                 190
#define IDB_PAGES_SMALL_HC              191
#define IDS_MYCALENDARS                 250
#define IDS_CALENDAR                    251
#define IDS_SHORTCUTS                   252
#define IDS_FOLDERS                     253
#define IDS_OUTLOOKBAR                  258
#define IDS_RIBBON_FILE                 260
#define IDS_RIBBON_NEW                  262
#define IDS_RIBBON_OPEN                 263
#define IDS_RIBBON_SAVE                 264
#define IDS_RIBBON_SAVEAS               265
#define IDS_RIBBON_PRINT                266
#define IDS_RIBBON_PRINT_LABEL          267
#define IDS_RIBBON_PRINT_QUICK          268
#define IDS_RIBBON_PRINT_PREVIEW        269
#define IDS_RIBBON_PRINT_SETUP          270
#define IDS_RIBBON_CLOSE                271
#define IDS_RIBBON_RECENT_DOCS          272
#define IDS_RIBBON_EXIT                 273
#define IDS_RIBBON_HOME                 274
#define IDS_RIBBON_CLIPBOARD            275
#define IDS_RIBBON_PASTE                276
#define IDS_RIBBON_CUT                  277
#define IDS_RIBBON_COPY                 278
#define IDS_RIBBON_SELECTALL            279
#define IDS_RIBBON_WINDOW               284
#define IDS_RIBBON_WINDOWS              285
#define IDS_RIBBON_STYLE                286
#define IDS_RIBBON_STYLE_TIP            287
#define IDS_RIBBON_STYLE_DESC           288
#define IDS_RIBBON_STATUSBAR            289
#define IDS_RIBBON_VIEW                 290
#define IDS_RIBBON_ACTIONS              291
#define IDS_RIBBON_TOOLS                292
#define IDS_RIBBON_FILETYPES            293
#define IDS_EDIT_MENU                   306
#define IDS_RIBBON_GOODWARE             310
#define IDS_RIBBON_MODELS               311
#define IDS_RIBBON_INDECES              312
#define IDD_LOGUI                       312
#define IDS_RIBBON_MALWARE              313
#define IDD_MAKEMODEL                   313
#define IDS_RIBBON_PREMALWARE           314
#define IDD_MAKEINDEX                   314
#define IDS_RIBBON_CLUSTERINGS          315
#define IDD_EXTRBUFFERS                 315
#define IDS_RIBBON_STUBMAPS             316
#define IDD_COMPILEMOD                  316
#define IDS_RIBBON_FINDOUTPUT           317
#define IDD_PRUNEMOD                    317
#define IDS_RIBBON_UNLABELED            318
#define IDD_MERGEMODEL                  318
#define IDD_FINDSIGS                    319
#define IDD_STUBMAP                     320
#define IDD_PREPROC                     321
#define IDD_CLSTFILES                   322
#define IDD_CFGDLG                      323
#define IDD_THRESHOLD                   324
#define IDD_SCHEDUI                     325
#define IDD_DIALOG1                     326
#define IDD_SELDEP                      326
#define IDR_MENU1                       327
#define IDR_RCLICK_MENU                 327
#define IDC_LOGLIST                     1001
#define IDC_LOGTEXT                     1002
#define IDC_EDIT1                       1003
#define IDC_EDIT_INP2                   1004
#define IDC_EDIT9                       1004
#define IDC_EDIT2                       1005
#define IDC_EDIT10                      1005
#define IDC_EDIT3                       1006
#define IDC_EDIT13                      1006
#define IDC_EDIT4                       1007
#define IDC_BTN_SELMODOUT               1008
#define IDC_EDIT12                      1008
#define IDC_EDIT11                      1009
#define IDC_EDIT14                      1009
#define IDC_EDIT15                      1010
#define IDC_SELDEP1                     1011
#define IDC_CHECK1                      1012
#define IDC_SELDEP2                     1012
#define IDC_SELDEP3                     1013
#define IDC_EDIT_MAKEIND_INP            1014
#define IDC_SELDEP4                     1014
#define IDC_EDIT16                      1014
#define IDC_COMBO_INDMODE               1015
#define IDC_EDIT17                      1015
#define IDC_BTN_SELINP1                 1016
#define IDC_BTN_SELINP2                 1017
#define IDC_BTN_SELOUT1                 1018
#define IDC_BTN_SELINP3                 1018
#define IDC_EDIT_MODE                   1019
#define IDC_BTN_CRCFG                   1020
#define IDC_EDIT5                       1021
#define IDC_BTN_SELINP6                 1021
#define IDC_BTN_SELMODINP2              1022
#define IDC_BTN_SELINP7                 1022
#define IDC_DEP_CMOD2                   1023
#define IDC_BTN_SELINP8                 1023
#define IDC_EDIT6                       1024
#define IDC_EDIT7                       1025
#define IDC_BTN_SELMODINP3              1026
#define IDC_DEP_CMOD3                   1027
#define IDC_EDIT8                       1028
#define IDC_CHECK2                      1029
#define IDC_BTN_ECFG                    1030
#define IDC_EDIT_PRUNE_INP              1031
#define IDC_EDIT_EXTRBUF_INP            1032
#define IDC_EDIT_COMPILE_INP            1033
#define IDC_EDIT_EXTRBUF_INP2           1033
#define IDC_EDIT_INP1                   1034
#define IDC_EDIT_EXTRBUF_INP3           1034
#define IDC_EDIT_OUT1                   1035
#define IDC_EDIT_EXTRBUF_INP4           1035
#define IDC_EDIT_SMIM2                  1036
#define IDC_EDIT_EXTRBUF_INP5           1036
#define IDC_BTN_SELSMINP3               1037
#define IDC_EDIT_EXTRBUF_INP6           1037
#define IDC_DEP_CSM3                    1038
#define IDC_EDIT_EXTRBUF_INP7           1038
#define IDC_BTN_SELSMINP4               1039
#define IDC_DEP_CSM4                    1040
#define IDC_BTN_SELINP4                 1041
#define IDC_BTN_SELINP5                 1042
#define IDC_SELDEP5                     1043
#define IDC_SELDEP6                     1044
#define IDC_BTN_SELFSOUT                1045
#define IDC_CHECK3                      1046
#define IDC_CHECK4                      1047
#define IDC_CHECK5                      1048
#define IDC_LIST3                       1049
#define IDC_BUTTON1                     1050
#define IDC_BTN_SELOUT                  1051
#define IDC_LIST1                       1052
#define ID_WRITE_PASTEASHYPERLINK       32770
#define ID_VIEW_GROAR                   32771
#define ID_VIEW_GOODWARE                32772
#define IDM_VIEW_GROAR                  32773
#define IDM_VIEW_GOODWARE               32774
#define ID_VIEW_MALWARE                 32775
#define IDM_VIEW_MODELS                 32776
#define ID_VIEW_INDECES                 32777
#define IDM_VIEW_INDECES                32778
#define ID_VIEW_MALWARE32779            32779
#define IDM_VIEW_MALWARE32779           32780
#define ID_VIEW_CLUSTERINGS             32781
#define IDM_VIEW_CLUSTERINGS            32782
#define ID_VIEW_STUBMAPS                32783
#define IDM_VIEW_STUBMAPS               32784
#define ID_VIEW_FINDSIGNATURESOUTPUT    32785
#define ID_VIEW_UNCLASSIFIED            32786
#define IDM_VIEW_FINDSIGS               32787
#define IDM_VIEW_UNCLASSIFIED           32788

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        328
#define _APS_NEXT_COMMAND_VALUE         32789
#define _APS_NEXT_CONTROL_VALUE         1053
#define _APS_NEXT_SYMED_VALUE           310
#endif
#endif
